# logging:
#   level:
#     org:
#       springframework: ERROR

spring:
  security:
    oauth2:
      client:
        provider:
          appsso:
            issuer-uri: xxxx
        registration:
          poop:
            provider: xxx
            client-id: xxxx
            client-secret: xxx
            scope: xxxx
            authorization-grant-type: xxx