logging:
  level:
    org:
      springframework: ERROR

org:
  springframework:
    cloud:
      bindings:
        boot:
          oauth2:
            enable: true

spring:
  security:
    oauth2:
      client:
        provider:
          appsso-demo-client-registration:
            issuer-uri: https://auth0-authserver.dev.h2o-2-22372.h2o.vmware.com
        registration:
          appsso-demo-client-registration:
            provider: appsso-demo-client-registration
            client-id: dev_appsso-demo-client-registration
            client-secret: cbff8134-6715-4a8e-b3f2-5111e5d59475
            scope: openid, developer.read, developer.write
            authorization-grant-type: client_credentials