# spring.security.oauth2.client.registration.okta.client-id=0oamoy46qy8naZ9Td5d6
# spring.security.oauth2.client.registration.okta.client-secret=QJHwlnkdynzcOvgdrwqen683tIZUswh9mvPNw23t
# spring.security.oauth2.client.registration.okta.authorization-grant-type=client_credentials
# spring.security.oauth2.client.registration.okta.scope=mod_custom
# spring.security.oauth2.client.provider.okta.token-uri=https://dev-9323263.okta.com/oauth2/default/v1/token
# spring.main.web-application-type=none


spring:
  security:
    oauth2:
      client:
        provider:
          appsso:
            issuer-uri: xxxx
        registration:
          appsso:
            provider: xxxx
            client-id: xxxx
            client-secret: xxxx
            scope: xxx
            authorization-grant-type: xxx