logging:
  level:
    root: DEBUG

spring:
  security:
    oauth2:
      client:
        provider:
          appsso:
            issuer-uri: xxxx
        registration:
          appsso:
            provider: xxxx
            client-id: xxxx
            client-secret: xxxx
            scope: xxx
            authorization-grant-type: xxx