logging:
  level:
    com:
      tappsso:
        client: INFO

spring:
  security:
    oauth2:
      client:
        provider:
          appsso:
            issuer-uri: xxxx
        registration:
          appsso-demo-client-credentials: # This has to match what's in the workload
            provider: xxx
            client-id: xxxx
            client-secret: xxx
            scope: xxxx
            authorization-grant-type: client_credentials