apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: appsso-demo-client-credentials-write
    apps.tanzu.vmware.com/workload-type: web
  name: appsso-demo-client-credentials-write
  namespace: dev
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  serviceClaims:
  # this name has to match the client registration ID you want to use in the SPRING CONFIG
  - name: appsso-demo-client-credentials
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: appsso-demo-client-credentials-write
  - name: ca-cert
    ref:
      apiVersion: v1 
      kind: Secret
      name: tap-ca 
  source:
    git:
      ref:
        branch: main
      url: https://github.com/x95castle1/client-credentials-appsso-client